# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'host-azure'
  demands:
  - npm

steps:
- checkout: self
  persistCredentials: true

- checkout: git://github.com/JonanXavi/prueba_azure.git
  persistCredentials: true

#- task: NodeTool@0
#  displayName: 'Instalar Node.js'
#  inputs:
#    versionSpec: '20.x'

- task: Npm@1
  displayName: 'Instalar dependencias'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Ejecutar pruebas de regresión con Cypress'
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'run runner-in-test-env:headless'